FROM alpine:latest AS builder

RUN apk add --no-cache --update nodejs npm

WORKDIR /usr/src/app

COPY package.json tsconfig.json ./

RUN npm install --production

RUN npm run clean && npm run tsc


FROM alpine:latest

RUN apk add --no-cache --update nodejs npm

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY dist package.json ./

EXPOSE 7001

CMD ["npm", "start"]
